language: python
python:
  - "3.6"
before_install:
  - pip install pipenv
install: 
  - pipenv install
script: 
  - pipenv check
  - cd ..
  - yamllint opensorcery/
#  - coverage run --source=reel setup.py test
#after_success:
#- coveralls
