---
services:
  - docker

jobs:
  include:
    - stage: code linting
      script:
        - docker run --rm -i hadolint/hadolint < Dockerfile
        - >
          docker run --rm
          -v ${PWD}:/lint_this
          sdesbure/yamllint
          yamllint /lint_this
    - stage: docker-compose up --build
      os: linux
      script: docker-compose up -d --build
      # - docker-compose run python manage.py test

# after_success:
# - coveralls
