---
language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker run --rm -i hadolint/hadolint < Dockerfile

    #install:
    #- pipenv install
    #

before_script:
  - docker-compose up -d

script:
  # The reason for the cd backwards and then running of yamllint is a small
  # problem I've found when runnign yamllint from the root of a dir. It won't
  # find the files. I've reported it on the yamllint repo.
  - cd opensorcery && python manage.py test
  #- pipenv check
  #- cd ..
  #- yamllint opensorcery/
  #- docker-compose build
  #- docker-compose run web python3 manage.py migrate
  #- odocker-compose up
# after_success:
# - coveralls
