---
language: python
python:
  - "3.6"
before_install:
  - pip install pipenv
install:
  - pipenv install
script:
  # The reason for the cd backwards and then running of yamllint is a small
  # problem I've found when runnign yamllint from the root of a dir. It won't
  # find the files. I've reported it on the yamllint repo.
  - pipenv check
  - cd ..
  - yamllint opensorcery/
#  - coverage run --source=reel setup.py test
# after_success:
# - coveralls
