---
services:
  - docker

jobs:
  include:
    - stage: code linting
      script:
        - docker run --rm -i hadolint/hadolint < Dockerfile
        - >
          docker run --rm
          -v ${PWD}:/yaml
          sdesbure/yamllint
          yamllint /yaml
        - >
          docker run --rm
          -v ${PWD}:/pycode
          flintci/pycodestyle
          /pycode
        - > 
          docker run --rm
          -v ${PWD}:/code
          opensorcery/bandit -r
          /code
    - stage: docker-compose up --build
      os: linux
      script: docker-compose up -d --build
      # - docker-compose run python manage.py test

# after_success:
# - coveralls
