---
version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-database
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    command: python3 opensorcery/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - .:/code
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    command: npm run dev 
    volumes:
      - .:/code
