---
version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    dockerfile: Dockerfile-backend
    command: python3 opensorcery/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  frontend:
    dockerfile: Dockerfile-frontend
    command: npm run dev 
