---
version: '3'

services:
  db:
    build:
      context: ./database
  backend:
    build:
      context: ./opensorcery
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./opensorcery:/code
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/code
    ports:
      - "8080:8080"
