# We don't supply a BucketName as it allows us to more effectively update the
# environment and we are beter off delegating naming conventions to Sceptre
# as it allows us to ascertain whether the infra was handmade or automated.

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties: 
      AccessControl: PublicRead
      AccelerateConfiguration:
        AccelerationStatus: Suspended
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: 
              - Authorization
            AllowedMethods: 
              - GET
            AllowedOrigins: 
              - "*" 
            MaxAge: 3000
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
